spring:
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
  liquibase:
    change-log: classpath:db/changelog/master.xml

